defaults:
  - judo_default

dataflow:
  nodes:
    - id: simulation
      path: dynamic
      inputs:
        task:
          source: benchmarker/task
          queue_size: 1
        controls:
          source: controller/controls
          queue_size: 1
      outputs:
        - states
    - id: benchmarker
      path: dynamic
      inputs:
        states:
          source: simulation/states
          queue_size: 1
        traces:
          source: controller/traces
          queue_size: 1
        plan_time:
          source: controller/plan_time
          queue_size: 1
      outputs:
        - task
        - optimizer
    - id: controller
      path: dynamic
      inputs:
        task:
          source: benchmarker/task
          queue_size: 1
        optimizer:
          source: benchmarker/optimizer
          queue_size: 1
        states:
          source: simulation/states
          queue_size: 1
      outputs:
        - controls
        - traces
        - plan_time

node_definitions:
  visualization: null  # deletes the viz node from judo defaults
  benchmarker:
    _target_: judo.app.benchmark.BenchmarkerNode
    node_id: benchmarker
    max_workers: null
    num_samples: 100
