task: cylinder_push
optimizer: cem

dataflow:
  nodes:
    - id: simulation
      path: dynamic
      inputs:
        sim_pause:
          source: visualization/sim_pause
          queue_size: 1
        task:
          source: visualization/task
          queue_size: 1
        task_reset:
          source: visualization/task_reset
          queue_size: 1
        controls:
          source: controller/controls
          queue_size: 1
      outputs:
        - states
    - id: visualization
      path: dynamic
      inputs:
        states:
          source: simulation/states
          queue_size: 1
        traces:
          source: controller/traces
          queue_size: 1
        plan_time:
          source: controller/plan_time
          queue_size: 1
      outputs:
        - sim_pause
        - task
        - task_reset
        - optimizer
        - controller_config
        - optimizer_config
        - task_config
    - id: controller
      path: dynamic
      inputs:
        sim_pause:
          source: visualization/sim_pause
          queue_size: 1
        task:
          source: visualization/task
          queue_size: 1
        task_reset:
          source: visualization/task_reset
          queue_size: 1
        optimizer:
          source: visualization/optimizer
          queue_size: 1
        states:
          source: simulation/states
          queue_size: 1
        controller_config:
          source: visualization/controller_config
          queue_size: 1
        optimizer_config:
          source: visualization/optimizer_config
          queue_size: 1
        task_config:
          source: visualization/task_config
          queue_size: 1
      outputs:
        - controls
        - traces
        - plan_time

node_definitions:
  simulation:
    _target_: judo.app.simulation.SimulationNode
    node_id: simulation
    max_workers: null
    init_task: ${task}
    task_registration_cfg: ${custom_tasks}
  visualization:
    _target_: judo.app.visualization.VisualizationNode
    node_id: visualization
    max_workers: null
    init_task: ${task}
    init_optimizer: ${optimizer}
    task_registration_cfg: ${custom_tasks}
    optimizer_registration_cfg: ${custom_optimizers}
    controller_override_cfg: ${controller_config_overrides}
    optimizer_override_cfg: ${optimizer_config_overrides}
    sim_pause_button: true
  controller:
    _target_: judo.app.controller.ControllerNode
    node_id: controller
    max_workers: null
    init_task: ${task}
    init_optimizer: ${optimizer}
    task_registration_cfg: ${custom_tasks}
    optimizer_registration_cfg: ${custom_optimizers}

custom_tasks: null
custom_optimizers: null
controller_config_overrides: null
optimizer_config_overrides: null
