name: Docs

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  docs:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4

      - uses: prefix-dev/setup-pixi@v0.8.10
        with:
          pixi-version: latest
          cache: true

      - name: "Set up Python 3.13"
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Building documentation
        run: |
          pixi run -e dev sphinx-build docs/source docs/build -b dirhtml

      - name: Deploy to GitHub Pages
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/build
          force_orphan: true
